# Generated by Django 6.0.1 on 2026-01-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
