# Generated by Django 6.0.1 on 2026-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('EEE', 'Electrical & Electronics'), ('ECE', 'Electronics & Comm'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IOT', 'Internet of Things')], default='AI', max_length=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('department', 'section', 'year')},
        ),
    ]
