# Generated by Django 6.0.1 on 2026-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_batch_department_batch_section_alter_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
