# Generated by Django 6.0.1 on 2026-01-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('EEE', 'Electrical & Electronics'), ('ECE', 'Electronics & Comm'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IOT', 'Internet of Things')], default='AI', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
