# Generated by Django 6.0.1 on 2026-01-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_subject_credits_subject_department_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
