# Generated by Django 6.0.1 on 2026-01-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
