# Generated by Django 6.0.1 on 2026-01-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_subject_credits_subject_department_subject_semester'),
        ('students', '0007_batch_department_batch_section_alter_batch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('period', models.IntegerField(choices=[(1, 'Period 1 (9:00 - 10:00)'), (2, 'Period 2 (10:00 - 11:00)'), (3, 'Period 3 (11:15 - 12:15)'), (4, 'Period 4 (12:15 - 1:15)'), (5, 'Period 5 (2:00 - 3:00)'), (6, 'Period 6 (3:00 - 4:00)'), (7, 'Period 7 (4:00 - 5:00)'), (8, 'Period 8 (5:00 - 6:00)')])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='students.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='faculty.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='faculty.subject')),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('batch', 'day', 'period')},
            },
        ),
    ]
