# Generated by Django 5.0.14 on 2026-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_id'),
        ('students', '0002_alter_batch_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'period')},
        ),
    ]
