# Generated by Django 6.0.1 on 2026-01-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancechangerequest_attendancesession_and_more'),
        ('faculty', '0001_initial'),
        ('students', '0006_student_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.batch'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
        migrations.AddField(
            model_name='attendancechangerequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('date', 'period', 'batch')},
        ),
    ]
